# Generated by Django 5.0.6 on 2024-05-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField()),
                ('price', models.IntegerField(blank=True, default=0)),
                ('is_exists', models.BooleanField(default=True)),
            ],
        ),
    ]
