# Generated by Django 5.0.6 on 2024-05-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0010_husband_women_husband'),
    ]

    operations = [
        migrations.AlterField(
            model_name='husband',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
