# Generated by Django 5.0.6 on 2024-06-03 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0013_alter_women_options_alter_women_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterModelManagers(
            name='women',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='women',
            name='content',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(5, message='min 5 symbols'), django.core.validators.MaxLengthValidator(100, message='max 100 symbols')]),
        ),
    ]
