# Generated by Django 5.0.6 on 2024-06-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0014_uploadfiles_alter_women_managers_alter_women_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%n/%d/', verbose_name='Фото'),
        ),
    ]
